spring:
  application:
    name: youngmarket
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/youngmarket
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  liquibase:
    change-log: classpath:db/changelog/master.xml

